### ISSUE TITLE
[3.0.0-M1] Action is ambiguous

### ISSUE THREAD

**Issue by rfranco** [slick/slick#1049]
I'm trying Slick 3 with Play and there is ambiguous name and i think that will be very common complaint as you can see in my simple example.

```scala
package controllers

import play.api.mvc._
import slick.driver.PostgresDriver.api._

class Foo extends Controller {

  val db = Database.forConfig("db.default")
  def all() = Action {
    val query = sql"select 1".as[Int]
    val result = db.withSession{ implicit session =>
      query.list
    }
    Ok(result)
  }

}
```
```bash
[error] reference to Action is ambiguous;
[error] it is imported twice in the same scope by
[error] import slick.driver.PostgresDriver.api._
[error] and import play.api.mvc._
[error]   def all() = Action {
```

Maybe it's better change the Action name for other thing.

**Comment by szeiger** [comment]
Yes, this is is already on the roadmap for 3.0. Also see the comments on #1021. The only problem is what to use instead of `Action`. My current thinking (which will have to come to a conclusion really soon) is that `IO` is the best alternative. It would conflict with scalaz but it's probably not as big of a problem (and I expect that scalaz users would be comfortable renaming one of the types to disambiguate).

**Comment by cvogt** [comment]
@szeiger DB instead of IO :)? Or DS for Data Source? Or Slick[...]?

**Comment by rfranco** [comment]
i agree that `IO` is not a good name. Need a name that give a idea of flow of action.

**Comment by szeiger** [comment]
@rfranco Except for being tied to a specific database, it matches a standard `IO` type (from Haskell or scalaz) in functionality. Instances of this type are universally called "I/O Actions", at least I couldn't find any other names on the web.

@cvogt Since everything in Slick is about DB or DS or Slick, such a type name wouldn't confer any useful meaning.

**Comment by szeiger** [comment]
The best suggestion that came up during brainstorming here at the team meetup is "Task"

**Comment by nafg** [comment]
DBAct (short for Action)?

**Comment by nafg** [comment]
Perhaps DBIO?

**Comment by szeiger** [comment]
I looked at some more related stuff, including Doobie which has monadic APIs at different levels of JDBC and all type names there end with IO, i.e. TransactionIO or ConnectionIO. In this light `DBIO` looks better and better to me. It's short, it has "IO" in it and we can still use the "action" terminology.

**Comment by cvogt** [comment]
I like DBIO

**Comment by rfranco** [comment]
+1 :+1:
