### ISSUE TITLE
bring back SQLServerDriver

### ISSUE THREAD

**Issue by fommil** [slick/slick#1052]
https://github.com/slick/slick/blob/b70a2c7289e9aa4f6e12cf7426c5a91d47e1b4bf/src/main/scala/scala/slick/driver/SQLServerDriver.scala

The decision to remove this file and put it behind a paywall was just insane from a community perspective. Please put it back.

**Comment by szeiger** [comment]
There are no plans to support closed-source database systems in the open-source core of Slick. Feel free to take the old version and port it to a newer Slick release (it's BSD-licensed after all).

**Comment by fommil** [comment]
We are forced to do that. Procurement orders in corporate environments are harder to obtain than time to rewrite entire frameworks. This typesafe decision is absolutely insane and is a massive own goal.

We would have contributed our findings about MS SQL intricacies back to typesafe but now we can't and we will actively prohibit you from including it in your commercial offering.

**Comment by cvogt** [comment]
Typesafe is funding the development of Slick, the money got to come from somewhere. Offering drivers for commercial database systems only as part of a commercial offering seems reasonable to me. To my (potentially outdated) knowledge the fees for the required Typesafe subscription are far lower than the fees to run these commercial database systems in production. This may harm Slick adoption, but maybe less than not having funding for the project. I am just saying I find the decision reasonable rather than insane.

**Comment by cvogt** [comment]
Plus as @szeiger pointed out it is a hurdle, not necessarily a blocker if you really can't pay for the subscription.

**Comment by fommil** [comment]
@cvogt you don't get it. Even if it was $5 for a license in perpetuity, the admin involved in getting it approved in a corporate environment is insurmountable. I can understand wanting to charge for the Oracle driver, but the MS one was already available and it has been retracted.

I had quite a hairy moment with my customer today when we realised that the driver was removed. It basically blocks Slick for the project and I'm managing to save my work as an anomaly by pulling the driver back from the grave. The time it took to workaround this was surely more than your fee, plus I'm now putting together a fix in my personal time on a Friday night!

You don't need to tell me about funding open source. Just have a look at my repositories on github to see that I give back heavily to the community. **This is the community you are in**. Indeed, typesafe are indirectly benefiting from my work. I bet you'd all be pretty damn pissed off if I just removed support for your deployment environments in netlib-java (which makes mathematics algorithms run a lot faster in Spark), and demanded a payment to give you back the key classes. Sure, you could compile everything yourself again... but you'd lose days.

It **is** insane and I am really quite furious.

**Comment by cvogt** [comment]
Sorry for the pain you suffered. @fommil For the record, I am not with Typesafe. I was with EPFL and now I am just an external, non-profit, open-source contributor to Slick. I was not involved in any of the marketing decisions.

**Comment by fommil** [comment]
:smile:

**Comment by hepin1989** [comment]
@fommil  wow,you are a man of caliber, of strength, and of character .

**Comment by fommil** [comment]
https://github.com/fommil/freeslick

**Comment by sibex** [comment]
@szeiger @fommil Microsoft would probably express this quite similar:
There are no plans to support open-source systems for our closed-source database.

Typesafe, don't be like Microsoft. Please.

**Comment by fommil** [comment]
What makes this doubly insane, is that I've had to give up my weekend to create the skeleton of a project that can deploy ONE TRIVIAL FILE so that this can remain free software. I'm going to have to give up many more weekends to maintain release branches that match the slick release schedule and keep pace with all the trivial changes to the driver API with each release. When all of this could easily piggyback off the standard slick release schedule.

I'll tell you this: my time that I would have been dedicating to maintaining/improving Typesafe stack components, such as https://github.com/fommil/netlib-java (used in Breeze and Spark) and integration of https://github.com/ensime/ensime-server into the Typesafe web Activator has suddenly dropped to the bottom of my TODO list.

I'm feeling completely disenfranchised by this and I'm seriously concerned about Typesafe's position as custodian of Scala.

**Comment by cvogt** [comment]
I'll bring this thread to Typesafe's attention to make sure they hear your positions.

**Comment by fommil** [comment]
@cvogt thanks!

**Comment by cvogt** [comment]
done

**Comment by derekhenninger** [comment]
Typesafe invests heavily in open source.  We also select a few areas where we determine there is reasonable distinction between open source solutions and commercial software.  In the case of SQLServer (and other close source databases) we have decided that it is appropriate for us to charge for the use of the Slick-SQLServer driver.  Clearly you are paying Microsoft for SQLServer and we believe it is reasonable for you to also pay Typesafe.  The subscription fees paid to Typesafe are reinvested in our product development, which enables us to deliver great open source software, like Slick.

**Comment by nafg** [comment]
You haven't addressed Sam's complaint. It's not about cost, it's about time
to approval.

**Comment by fommil** [comment]
@derekhenninger I'm going to take this offline through TypeSafe channels. I also invest in open source and I will not be cooperating with TypeSafe until this matter is resolved. You've basically broken the implied community of trust here.

**Comment by szeiger** [comment]
@nafg We removed SqlServerDriver in Slick 2.0 which was released in January 2014. This change was officially announced in May 2013 (3 months after the release of Slick 1.0.0), giving users ample time to prepare. Users who already used it in production at that time were given a free license.

**Comment by fommil** [comment]
I'm aware of all that, it doesn't change a thing.

**Comment by fommil** [comment]
BTW, 3 months may be "ample" time for a startup to change but not realistic for a large corporation.

**Comment by sibex** [comment]
Wow! So all you are saying is that the MS-SQL users should pay for the development of the free Postgresql driver? Because Microsoft customers are rich morons and should always pay twice, for the database **and** the driver? On the other hand all the developers with fancy $3K Apple MBP are cool and shouldn't pay at all, because they are using (commercially) an open source database?

Actually the MS SQL Server Express is absolutely free of charge and widely used on many MS Windows based web servers on the intra- and internet. A combination of Play/Spray and Slick would have been a reasonable choice for replacing legacy ASP.NET web apps. And it's still a good choice because the driver is no rocket science as @fommil demonstrated. So no sane person will pay _$xxxxx_ to you only to get a 100 LOC driver. But after **this** hostile _cash-cow_ debacle some developers may think twice before they buy a subscription from you. Congrats to the Typesafe marketing team! What will you call the users of Typesafe OSS without a subscription next? Freeloaders?

**Comment by fommil** [comment]
There is also a major concern here about the freedom of the software: these things are taken for granted in OSS stacks.

My team would not use the TypeSafe proprietary "driver" for their production databases, end of story. Even if the politics and approval process was easy. We need to know the exact semantics for the SQL that is being created, and we need to be able to modify it when it breaks. Proprietary software restricts users on both accounts. Incidentally, we use [http://jtds.sourceforge.net/](JTDS) even though the company pays the hefty PROD/QA MS-SQL licenses, for this same reason.

**Comment by szeiger** [comment]
@sibex It is a perfectly valid choice for an enterprise to rely only on open source software and avoid proprietary software and support. If we didn't agree with this, we would not make most of our software available under very liberal licenses. However, you need to be aware of the trade-offs when you make such a decision. In particular, free software does not come with free long-term support, so you either need to pay a vendor for support or be prepared to do it yourself.

**Comment by fommil** [comment]
We all thought that TypeSafe's business model was a free software stack with paid-for support and consultancy, including contractual proprietary development. This model is clearly not true, and I for one do not know what your game is anymore, especially when it involves closing down free software and selling licenses to proprietary software at the very core of that previously open source stack.

**Comment by szeiger** [comment]
@fommil Our main product is the Typesafe Reactive Platform, which includes certified and supported builds of our open source project, plus additional proprietary software: http://typesafe.com/products/typesafe-reactive-platform

**Comment by sibex** [comment]
@szeiger I absolutely understand the implications. The price for an Oracle MySQL subscription is $10K - $30K per year and yet the full-fledged slick MySQL driver can be used in production for free. Any company using MySQL can decide on their own if they want to buy certified and supported builds from Typesafe. On the other hand if they want to use slick(-extensions) in production with any version of MS-SQL they are obligated to buy the Typesafe subscription, even when the application is not mission critical at all. The argument _clearly you are paying X for Y and we believe it is reasonable for you to also pay Typesafe_ is baloney. It's none of Typesafe business how much a company pays Microsoft, Oracle or anybody else.

**Comment by godenji** [comment]
I suspect most enterprise clients don't bat an eye at the licensing fees levied by Typesafe for the closed source drivers -- just the cost of doing business.

Saying that, ideally everything would be free and without restriction, but Typesafe is a for proft entity (IIRC); finding ways to monetize their products and services shouldn't come as a surprise. At minimum they need to pay their staff, which is to say, no staff, no Slick.

I can see where the cons are coming from in this thread, but if you're already paying through the nose for closed source licenses, well, you've got deep pockets (unlike the open source license crowd which more often than not has little in the way of financial resources). Basically the money has to come from somewhere...

**Comment by derekhenninger** [comment]
There are a number of statements in this thread about how Typesafe should run it's open source business.  I found this presentation from Marten Mickos to be an excellent overview of various approaches to open source business models: http://www.heavybit.com/library/video/2013-10-15-marten-mickos.  Perhaps others will find it interesting.

**Comment by fommil** [comment]
@derekhenninger I wouldn't presume to advise you on business strategy, so please do not take my words out of context when I express what is the presumed common wisdom of TypeSafe's business model. I am, however, extremely concerned about this "bait and switch" tactic of having a Free Software stack and then making trivial core components proprietary. If I were to do that to you with my free software, which **is** part of your Spark stack, I'm quite certain that you and your customers would be equally frustrated and lose trust. I won't be doing that, because I'm a strong believer in Free Software.

**Comment by sibex** [comment]
@derekhenninger Great overview from Marten Mickos. I see your point. But Typesafe has made the decision to venture a transition from Microsoft .NET to the Typesafe Reactive Platform much more difficult by closing down the MS-SQL driver in Slick. This _[Convince your boss](http://go.typesafe.com)_ thing does not work so well when she has to pay for the Typesafe subscription from the very first LOC, develop a proprietary MS-SQL driver or change the database vendor.

> [...] so of course he would build Facebook on the LAMP Stack. They were a big non-paying user for the longest time, and one day they came to us and said, "Our business is growing so fast, we have so much to do. Why do we have all these people here maintaining our MySQL databases? Could we buy a support contract and the services from you to keep the site going?"

**Comment by cvogt** [comment]
@sibex Typesafe's sql server driver is free for use during development. Production use requires a license. Plus there is @fommil's open source alternative now. So that means if you care for Typesafe having your back when you run into problems you can get a subscription, if you are happier on your own, use the open source one.

Looks like we have exhausted this topic and heard everyone's positions. Thank you for a healthy discussion guys.

**Comment by urquilla** [comment]
I'll just point out that is not the driver the real concern.

Either way, I'll be wary from now on of whatever core functionality could be dropped in the near future.

As @fommil  said.
>I am, however, extremely concerned about this "bait and switch" tactic of having a Free Software stack and then making necessary core components proprietary.

**Comment by cvogt** [comment]
Bait and switch implies that Typesafe purposely tried to lure people in to let them pay later. That is not how I experienced it. It seemed more like part of the effort of Typesafe trying to figure out their business model.

**Comment by Tmr** [comment]
> Bait and switch implies that Typesafe purposely tried to lure people in to let them pay later. That is not  how I experienced it. It seemed more like part of the effort of Typesafe trying to figure out their  business model.

I traced Slick from very beginning and I experienced it somewhat different, of course not as a fraud or a lie but as a dangerous sign. And while I think that Typesafe stack is great (and Slick in particular) I excluded Slick from all of my projects (regretfully), because of several reasons, and one of them is that I suspect that "trying to figure out their business model" is not ended.

If Typesafe will officially express clear position about future of Sliсk it probably would dispel worries like this (If such a statement was made, please, let me know).

**Comment by SRGOM** [comment]
@fommil Its easy to shout typesafe down on a public forum so that you can hurt their PR, why don't you fight with the firm that employs you, their finance policies are draconian. I hope you realize everyone has to pay bills. 
You're being indignified here, and are trying to justify it by pointing out your contributions. You act like Typesafe owes anyone anything- they don't. Just like you don't and are writing open source as a favour. I have nothing to do with typesafe, btw

**Comment by fommil** [comment]
@SRGOM nobody except TypeSafe can make that source code available again. It is unacceptable to do this in an OSS stack.

**Comment by SRGOM** [comment]
@fommil I'd like to say that stands like yours are the problem some corporations are afraid of open source. You take them for granted, and go against their interests. Typesafe is composed of people like you and I who need to pay their bills, and Its a great organization that's doing it by doing something worthwhile, not creating your yo and snapchats. But you're hurting them by taking their source and misusing the license. Sure you're following the word, but definitely not the spirit. You're hurting open source because you cannot wade through your firm's bureaucracy.

**Comment by SRGOM** [comment]
@fommil Actually, I don't think OSS licenses can' be revoked. I believe Typesafe did all the work and if they decide to change the license, its their choice. I really hope they sue you so that you can stop hurting Open source. You're setting a wrong precedent here- scaring firms into releasing their proprietary tech

**Comment by cvogt** [comment]
@SRGOM AFAIK @fommil based his work on an old version of the driver, which was released as free software. Derivative forks being legal and actually encouraged is what free software is all about.

Guys, let's take this topic to rest. I think everything that could have been said has been said. Thanks for the discussion.

**Comment by fommil** [comment]
:+1: to what @cvogt said

**Comment by SRGOM** [comment]
@cvogt Fine, but as an academic inquiry: does this mean that if I ever release a piece of code accidentally, its forever open source?

**Comment by cvogt** [comment]
@SRGOM no, most countries have copyright laws. Your code belongs to you unless you explicitly give up your rights. That's why free software projects come with licenses that give up certain right. Slick comes with a BSD-style license.

**Comment by sibex** [comment]
@cvogt :+1: Thank you for the clarification. I can't believe someone with a github account would think that forking is actually _stealing code_.

**Comment by kasajian** [comment]
Please keep the following in mind with Open Source software in general.

1.  If you're the author, you own the copyright.  Even with the GPL, license you can release say version 1.0 of your software simultaneously as GPL, BSD, MIT and commercial.

Let's assume the most restrictive GPL license is being used.

2.  You then release version 2.0 of your software as commercial only.  You can do that because you're the copyright owner of the software.   even though 1.0 was release under GPL.

3.   Now, someone else cannot take your 1.0 and release their own version as a commercial version because of the GPL license.

However, more permissive Open Source license will allow you to do that.   Each version a new copyright work.

Please remember the following:
1.   Just because someone release version 1.0 as Open Source, they are obligated to release all future versions as Open Source.   They're not.  They're not obligated to release any versions at all.   And someone else can easily take their 1.0 version, package it up and release it as their own commercial version, not Open Source.    Unless it's something restrictive such as GPL.

2.  A company is allowed to change their business model.  It is not bait-and-switch for them to change the license for a new version of their software.   They're not changing the license of an already existing version.   That version is still whatever license it was released under.

3.   If they are using a permissive Open-Source license, ANYONE can take their software and re-release it as their own commercial version.   If you don't think someone should not be allowed to do that, then you are saying you don't agree with permissive licenses.   In that case, you can join the GPL crowed.   But just call it what it is.    However, if you agree that ANYONE can take their software and re-release it as their own commercial version, then surely the original author can do the same, which is what they've done.

Any open-source non-GPL project can do this..   Even GPL projects can do that as long as the copyright holder is the one doing it.

**Comment by DanielJoyce** [comment]
I guess my biggest problem is the total lack of transparency wrt pricing. We plan on shipping a server product to end customers. With no idea of cost for commercial DB support, I guess I will go with JOOQ as the cost is only per developer desktop.

**Comment by fommil** [comment]
@cvogt can you please open again, remove the `WontFix` label, and ceremoniously close this? :smile:

http://slick.typesafe.com/news/2016/02/01/slick-extensions-licensing-change.html

**Comment by fommil** [comment]
:grinning:

**Comment by cvogt** [comment]
How's that?
```
      _______  _____  _______ _______
      |______ |     | |______ |______
      |       |_____| ______| ______|
           *      *    .   *    .
                ..  *    o
              o   *  .    *
                ________
               (________)
               |    o   |
               | o    o |
               |   o    |
               | o    o |
               | o  o   |
               |      o |
               ( o      )
                \   o  /
                 \    /
                  \  /
                   ||
                   ||
                   ||
                   ||
                   ||
                ___||___
               /   ||   \
               \________/
```
