### ISSUE TITLE
possible soundness problem reading Array[Short] in postgres

### ISSUE THREAD

**Issue by tpolecat** [slick/slick#1072]
Hi guys, just FYI, I had a conversation with someone in `#scala` today on IRC who was using the Postgres extension and found that reading into a `List[Short]` was actually handing him an ill-typed `List[Int]` which would blow up with a `ClassCastException` later on when you examine the elements. I discovered this when working on doobie so I think it's legit; when you read an array of small ints you always get back an `Array[java.lang.Integer]`. My solution was to just not support a mapping for `Array[Short]` with Postgres. Anyway you might take a look. Ping me if you need more info.

**Comment by szeiger** [comment]
@tpolecat Thanks for the heads up. I don't think this can occur in Slick because we're using the correct primitive acessors for all primitive types (see https://github.com/slick/slick/blob/2.1.0/src/main/scala/scala/slick/driver/JdbcTypesComponent.scala#L193-198). This is done for two reasons, one being that the return type of getObject() is not very reliable across database systems and database types (as you discovered). The other reason is performance. By writing a fast path converter, you can get primitive values from JDBC all the way through Slick's type mappings and into your entity classes without boxing (e.g. https://github.com/slick/slick/blob/2.1.0/slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/JdbcMapperTest.scala#L386-389).

**Comment by tpolecat** [comment]
Hi @szeiger this is specifically for reading `_int2` aka `smallint[]` array columns, where you expect to see `Array[java.lang.Short]` which as far as I know you can only get via `getObject` and casting, and the cast is unsound because you get a `Array[java.lang.Integer]` back.

**Comment by szeiger** [comment]
Ah, I see. Was this with https://github.com/tminglei/slick-pg/ ? Slick does not support array values on its own.

**Comment by tpolecat** [comment]
Oh, yes I think it was. The person said `slick-pg` and I thought it was a standard extension. I'll move this issue over there. Sorry for the bother!
