### ISSUE TITLE
Slick 3.0 DBIO andThen combinator

### ISSUE THREAD

**Issue by n3ziniuka5** [slick/slick#1090]
from scaladoc:
`Run another action after this action, if it completed successfully, and return the result of the second action.`
However, the `andThen` block runs every time, regardless of the status of the previous action. The action itslef is not run if the previous action failed, but the block is run every time, unlike `flatMap`.

Was this intended or not? If yes, I think it should be reflected in the scaladoc, which I have no problem updating myself. Also, if it is intentional, what is the reason for this? This may cause some issues if you are not aware of this behavior and you want to run some additional non-db actions(along with a db action) if the previous action succeeds.

**Comment by szeiger** [comment]
There is no block to run. `andThen` takes a `DBIOAction` value. If you put a block of code in this place, it will just run on the caller thread before `andThen` is even invoked. And yes, this is intentional. Making `andThen` strict is the only reason for having it in the first place. By not having to run any computation between the two actions, it doesn't need to switch ExecutionContexts or reacquire a database connection. If both actions are synchronous database actions, they get fused.

**Comment by n3ziniuka5** [comment]
Ok, I see the purpose of this now. So I guess you shouldn't do something like
```
someDBIO.andThen({
  saveSomethingToFile()
  anotherDBIO
}) 
```
However doing such things feels very natural with `andThen` combinator. I guess the scaladoc could say:
`Run another action after this action, if it completed successfully, and return the result of the second action. Do not include any non-database computations as those will be executed regardless.`
