### ISSUE TITLE
Amazon Redshift support: Backticks escaping

### ISSUE THREAD

**Issue by sjbog** [slick/slick#1328]
When I try to query redshift I get:
```
[Amazon](500310) Invalid operation: syntax error at or near "`"
```
What is the proper driver or how can I omit escaping table and column names with backticks?

I use
```
driver = "slick.driver.PostresDriver$"
db.driver = "com.amazon.redshift.jdbc41.Driver"
```
slick v3.1.0
play v2.4.x

**Comment by cvogt** [comment]
Not having experience with Redshift I read that they claim to be compatible with the Postgres JDBC drivers, which Slick is using underneath. So you can probably just use `db.driver = "org.postgresql.Driver"` and add the required dependency `"postgresql" % "postgresql" % "9.1-901.jdbc4"`.

Otherwise patching Slick's Postgres driver may help: See https://github.com/slick/slick/blob/3.1/slick/src/main/scala/slick/driver/PostgresDriver.scala

**Comment by cvogt** [comment]
turned into feature request as this is currently not officially supported

**Comment by szeiger** [comment]
This doesn't look right. Only MySQLDriver uses backticks for quoted identifiers. All other drivers use double quotes.

**Comment by dant3** [comment]
Note that you should use something like `"postgresql" % "postgresql" % "8.0-318.jdbc3"` as Amazon say that you should use postgresql 8.0.2.

**Comment by cvogt** [comment]
thx @dant3 - updated my above comment

**Comment by sjbog** [comment]
Found the issue, thank you everyone.
Issue was in wrong driver's api imports, changed to `PostresDriver.api._` and it worked.

Whole setup:
```
"com.amazon.redshift" % "jdbc41" % "1.1.7.1007" % "test" from "https://s3.amazonaws.com/redshift-downloads/drivers/RedshiftJDBC4-1.1.7.1007.jar"

driver = "slick.driver.PostresDriver$"
db.driver = "com.amazon.redshift.jdbc41.Driver"

import slick.driver.PostresDriver.api._
```
