### ISSUE TITLE
add DBIOAction.collect

### ISSUE THREAD

**Issue by hepin1989** [slick/slick#1334]

**Comment by szeiger** [comment]
I wonder what the actual use cases are. I only added `filter` for compatibility with `Future.filter`. Only `withFilter` should really be needed for the cases where a for comprehension leads to a non-irrefutable pattern match. Since the DBIO monad doesn't have a zero, `collect` would differ from `map` only in the kind of Exception it throws.

**Comment by hepin1989** [comment]
so you think emit an exception is an bad idea?
yes,filter is more safe .

**Comment by szeiger** [comment]
I think both `filter` and `collect` are equally useful or useless in this context. It would make sense to either add `collect` or remove `filter`. Maybe @viktorklang remembers why scala.concurrent.Future has these methods?

**Comment by hepin1989** [comment]
I think collect maybe helpful that I could inspect the value and then throw an exception later do a clean up/finally or something like that ,otherwise ,I think that maybe ignored some context information,even I am not encounter this issue,but maybe in somewhere,it helps.

**Comment by cvogt** [comment]
If you don't have a use case, I'd suggest not adding it. Regarding removing filter, do we have a use case for filter? Haskell has filter on their monads, too, also for pattern matching, but I have seen discussions of this being a mistake, because in many cases the only thing you can do is throw an exception. I would be in support of deprecating it, if we don't see a use case and see if anyone complains. We can still consider changing our minds if somebody comes up with a good use case.

**Comment by szeiger** [comment]
I'm not writing enough Haskell code to judge it from a practical POV but in theory it seems wrong to me. Only a monad with zero should have `filter`. Scala uses `withFilter` for pattern matching in for comprehensions, so that's no excuse for supporting `filter`. Since `collect` can be expressed through `map` and `filter` I view it as the same case.

`scala.concurrent.Future` has both methods and supporting the complete purely functional subset of `Future`  combinators is a worthwhile goal on its own. If there are use cases for these methods on `Future` they probably apply to `DBIO`, too. Unless someone wants to chime in and proclaim that adding these methods to `Future` was a mistake and they are going to be removed, I'd be OK adding `collect` to `DBIO`, too. The differences to `map` would be that it requires a `PartialFunction` instead of a `Function1` and a failure to match would fail the computation with a `NoSuchElementException` instead of a `MatchError`.

**Comment by cvogt** [comment]
sounds reasonable +1 to that

**Comment by hepin1989** [comment]
I am using code like this:
```scala
 def deltasForAppVersion(game: String, channel: String)(appVersion: String) = {
    val deltasAction = for {
      bottomAssetVersionOption <- Tables.Release.filter(entity => entity.game === game &&
        entity.channel === channel && entity.appVersion === appVersion).take(1).result.headOption
      deltas <- bottomAssetVersionOption match {
        case Some(row) =>
          val assetVersion = row.assetVersion
          Tables.Delta.filter(entity => entity.game === game && entity.channel === channel && entity.end === assetVersion)
            .sortBy(_.start).result
        case None =>
          DBIO.failed(new IllegalArgumentException(s"no release record found for game:[$game],channel:[$channel] with app version :[$appVersion]"))
      }
    } yield deltas
    db.run(deltasAction)
  }
```
and I think If I have collect I could make use of it here.

**Comment by viktorklang** [comment]
@szeiger s.c.Future has filter, withFilter and collect. filter & collect are great to have for "transformation-style fluent coding", and `withFilter` is required if one doesn't want some pretty nasty warnings printed when using for-comprehensions.

We explicitly mimick the behavior of something like List in the implementation, but carry the exception forward rather than throwing it. (Hence the, NoSuchElementExceptions and whatnot.)

I'm not sure that answers the question but at least that is what my mind tells me right now.
