### ISSUE TITLE
DBIOAction cannot return Future[Object].

### ISSUE THREAD

**Issue by rchatsiri** [slick/slick#1440]
I'm creat trait support table from mysql use name `SalesmanProfileModel`. I found problems after class was implemented in name `SalesmanProfilesDAO` show error in method `def createSalemanProfile(...)`.

An error  show on `db.run(salesmanAction)`  is 

> type mismatch;  found   : slick.dbio.DBIOAction[Object,slick.dbio.NoStream,slick.dbio.Effect.Read with slick.dbio.Effect.Write]  required: slick.dbio.DBIOAction[com.gbuff.core.ordersystem.model.profile.SalesmanProfileModel.SalesmanProfileRow,slick.dbio.NoStream,Nothing]

How to convert `slick.dbio.Effect.Read with slick.dbio.Effect.Write` to `Nothing`?

```
trait SalesmanProfileModel{
  val profile: slick.driver.JdbcProfile
  import profile.api._
  import slick.model.ForeignKeyAction
  // NOTE: GetResult mappers for plain SQL are only generated for tables where Slick knows how to map the types of all columns.
  import slick.jdbc.{GetResult => GR}

  /** DDL for all tables. Call .create to execute. */
  lazy val schema: profile.SchemaDescription = Array(salesmanProfile.schema).reduceLeft(_ ++ _)
  @deprecated("Use .schema instead of .ddl", "3.0")
  def ddl = schema

  case class SalesmanProfileRow(id: Int, username: String, saleid: Int, createDate: java.sql.Timestamp, password: String, status: String)

  /** Table description of table salesman_profile. Objects of this class serve as prototypes for rows in queries. */
  class SalesmanProfile(_tableTag: Tag) extends Table[SalesmanProfileRow](_tableTag, "salesman_profile") {
    def * = (id, username, saleid, createDate, password, status) <> (SalesmanProfileRow.tupled, SalesmanProfileRow.unapply)
    /** Maps whole row to an option. Useful for outer joins. */
    def ? = (Rep.Some(id), username, saleid, createDate, password, status).shaped.<>({r=>import r._; _1.map(_=> SalesmanProfileRow.tupled((_1.get, _2, _3, _4, _5, _6)))}, (_:Any) =>  throw new Exception("Inserting into ? projection not supported."))
    /** Database column id SqlType(INT), AutoInc, PrimaryKey */
    val id  = column[Int]("id", O.AutoInc, O.PrimaryKey)
    /** Database column username SqlType(VARCHAR), Length(50,true), Default(None) */
    val username  = column[String]("username", O.Length(50,varying=true))
    /** Database column saleid SqlType(INT), Default(None) */
    val saleid  = column[Int]("saleid")
    /** Database column create_date SqlType(DATETIME), Default(None) */
    val createDate = column[java.sql.Timestamp]("create_date")
    /** Database column password SqlType(VARCHAR), Length(100,true), Default(None) */
    val password  = column[String]("password", O.Length(100,varying=true))
    /** Database column status SqlType(VARCHAR), Length(100,true), Default(None) */
    val status  = column[String]("status", O.Length(100,varying=true))
  }
     /** Collection-like TableQuery object for table SalesmanProfile */
  lazy val salesmanProfile = new TableQuery(tag => new SalesmanProfile(tag)) 

}
```

``````
import slick.ast.GetOrElse
import com.gbuff.core.ordersystem.db.DatabaseConfig
import scala.concurrent.ExecutionContext   

object SalesmanProfilesDAO extends SalesmanProfileModel with DatabaseConfig { 

  def getSalemanProfileFromUsername(username: Option[String])(implicit e :ExecutionContext) :  scala.concurrent.Future[Seq[SalesmanProfileModel.SalesmanProfileRow]] = {
    import  driver.api._  
    db.run(SalesmanProfileModel.salesmanProfile.filter(sp => sp.username === username).result)  
  }

  def createSalemanProfile(spRow :SalesmanProfileModel.SalesmanProfileRow)(implicit e :ExecutionContext)  : scala.concurrent.Future[SalesmanProfileModel.SalesmanProfileRow]  = {
    import  driver.api._    
     val salesmanAction  = SalesmanProfileModel.salesmanProfile.filter(sp => sp.username === spRow.username ).result.headOption.flatMap{
        case Some(SalesmanProfileModel.salesmanProfile) => 
            DBIO.successful(SalesmanProfileModel.salesmanProfile)
        case None =>
         val spRowId  =
            (SalesmanProfileModel.salesmanProfile returning SalesmanProfileModel.salesmanProfile.map(_.id)) += SalesmanProfileModel.SalesmanProfileRow(
            0,
            spRow.username ,
            spRow.saleid,
            spRow.createDate ,
            spRow.password ,
            spRow.status 
            )

          val spRowResult  = spRowId.map { id => SalesmanProfileModel.SalesmanProfileRow(
            id,
            spRow.username ,
            spRow.saleid,
            spRow.createDate ,
            spRow.password ,    
            spRow.status 
          )
        }
      spRowResult
    }
    val result :  scala.concurrent.Future[SalesmanProfileModel.SalesmanProfileRow] =   db.run(salesmanAction)
    result
  } 
}```
``````

**Comment by v6ak** [comment]
> How to convert slick.dbio.Effect.Read with slick.dbio.Effect.Write to Nothing

You can convert any value to Nothing using function `(_: Any) => ???`. But maybe this is not what you want ;)

First, it would be good to understand what Nothing is. And your question does not sound like you do understand it. (No offense.) Nothing is a quite common type in the Scala ecosystem. In some cases, it is pretty useful and adds some power to the typing system (e.g. Seq() is Seq[Nothing], so Scala compiler will know that calling head or similar method will never complete). Nothing can be useful when using exceptions, for example type of expression `if(a) 2 else sys.error("something is wrong")` is an union of Int and Nothing. Since Nothing is subtype of any other type, the union type if still Int. This is correct, because the expression always returns Int **if it returns**. The Nothing type if thus exact opposite of Any type in some sense.

The run method's type declaration is `def run[R](a: DBIOAction[R, NoStream, Nothing]): Future[R]`. Thus it requires DBIOAction with Nothing as the third parameter. However, type parameters might be [covariant/contravariant/invariant](http://docs.scala-lang.org/tutorials/tour/variances.html). The DBIOAction is defined as `DBIOAction[+R, +S <: NoStream, -E <: Effect]`. The “-” before E means that E is contravariant. So, we can pass to the run method a DBIOAction with E parameter of some more generic type than Nothing. Since Nothing is subtype of every type (i.e. Nothing is the most specific type), any type can be used there. In other words, the type `slick.dbio.Effect.Read with slick.dbio.Effect.Write` is OK at this place.

    actual:   DBIOAction[Object,             NoStream, Effect.Read with Effect.Write]
    variance:            +                   +         -
    required: DBIOAction[SalesmanProfileRow, NoStream, Nothing]
    status:              incompatible        same      compatible

As you can see, just the first parameter is of incompatible type (you pass a more specific type to a covariant parameter, which is what you can't). Other two parameters are compatible. In other words, the problem is that salesmanAction is a DB action that can be evaluated as Object, but you require it to be evaluated as SalesmanProfileModel.SalesmanProfileRow. It seems that the union type of `case Some(SalesmanProfileModel.salesmanProfile) =>` and `case None =>` is wrong.

BTW, why are you using `new TableQuery(tag => new SalesmanProfile(tag)) ` instead of `TableQuery[SalesmanProfile]`?

Well, such discussion probably should have been started in https://groups.google.com/forum/#!forum/scalaquery rather than there.
