### ISSUE TITLE
Support for Postgres Index with "WHERE" clause

### ISSUE THREAD

**Issue by yukw777** [slick/slick#1535]
My Postgres database has this unique constraint:
```create unique index on my_table (actual) 
where actual = true;```

But seems like this is not supported by Slick. Any other way to do this?

**Comment by cvogt** [comment]
@yukw777 do you mean when generating DDL from table defs?

**Comment by tminglei** [comment]
@cvogt I think @yukw777 expect to use slick table's index method to declare function index.

There're two related issue/PR: tminglei/slick-pg#233, tminglei/slick-pg#243.

I suggested to use plain sql to resolve it, since it's not easy to implement and use, and I don't think all functions should be implemented with slick Lifted API.

**Comment by cvogt** [comment]
Agreed. Personally I think a more workable way than writing your schema in Slick and creating DDL is going database first and using the code generator to generate the Slick code for it.

Closing this as wontfix pointing to plain SQL as a solution.
