### ISSUE TITLE
slick-codegen runs INIT scripts multiple times

### ISSUE THREAD

**Issue by jbdeboer** [slick/slick#1543]
(reopen of #1540)

When using H2, codegen will connect the h2 in-memory database multiple times, causing the INIT script to run more than once.
## Steps to reproduce:
1. Configure slick-codegen using an H2 in-memory database and an INIT script (this is the recommended approach) e.g. pass the following URL to `slick.codegen.SourceCodeGenerator`: "jdbc:h2:mem:test;INIT=runscript from 'src/main/sql/create.sql'"
2. In `create.sql`, create a table, e.g. `CREATE TABLE puppies`
3. Run the codegen and notice that it fails with "Table "puppies" already exists.
## Analysis:

This issue has a couple contributing factors:

First, h2 will run INIT scripts each time a connection is opened instead of once per database. This is not unexpected behaviour and will be rectified by https://github.com/h2database/h2database/pull/313

Second, slick-codegen opens multiple connections to the database. Along with triggering the h2 bug, this implementation is complicated and inefficient.

**Comment by cvogt** [comment]
Are you sure that's what is happening? The example project is using an in-memory database. The INIT is only needed for demo purposes, because there the database is in memory and disappears when the connection to is closed and needs to be recreated every time we reconnect. In a real situation this would obviously not be the case, but having a persistent database up would be hard in such an example application. 

Without reviewing the codegen code for multiple connections, I that that is actually not the case. What happens instead is: Slick opens one connection during sbt's source generation phase here https://github.com/slick/slick-codegen-example/blob/3df9e26bb9aa7b992dd704c72e34e0e28159f426/build.sbt#L23 and another one later at runtime here https://github.com/slick/slick-codegen-example/blob/3df9e26bb9aa7b992dd704c72e34e0e28159f426/src/main/scala/Example.scala#L18

This is how things would play out in reality as well. In the demo the database should disappear between the two connections, so using INIT should be fine.

Did you modify anything else in the demo code that would make the database stick around? Or maybe a global h2 setting is responsible. Regardless I recommend switching away from an in-memory database and from doing INIT side effects during creating the connection and use a persistent database instead if you want to do anything more than just play with the demo.

Let me know if that helped.

**Comment by jbdeboer** [comment]
The two connections are opened from the JdbcDataSource.

The first at line 70: https://github.com/slick/slick/blob/0a8a5d7e0124f2d588bb44cc0ccd981bb92295ff/slick/src/main/scala/slick/jdbc/JdbcDataSource.scala#L70

The second at line 73.

h2 clients, such as slick, should be able to make multiple connections to a database. There is an h2 bug here where the second connection triggers the INIT script a second time on the same in-memory database.

But, in the slick-codegen case, ```keepAliveConnection```'s approach of creating a second, unused, connection is bulky and confusing. A better approach would be to use a pinned database connection for all actions and remove the ```keepAliveConnection``` code path entirely.

Personally, I want to create Table definitions from a SQL file as an sbt task without depending on a persistent database. From what I've read, using a h2 database with an INIT option is the best-supported solution (e.g http://slick.lightbend.com/doc/3.0.0/code-generation.html). If this is not recommended; I'd be happy to look at another solution.

**Comment by cvogt** [comment]
@jbdeboer I see. I understand better now, thx for the info. Since you have an idea how to handle this better, do you want to take a stab at fixing this?

**Comment by jbdeboer** [comment]
Yes, I will send a PR shortly.

**Comment by hvesalai** [comment]
Any PR? Can you link it to this issue and reopen.

**Comment by jbdeboer** [comment]
Clearly not. I'm not sure what happened and I don't have a fork anymore.
