### ISSUE TITLE
Transaction (and atomicity) when composing in futures does not work

### ISSUE THREAD

**Issue by bcatarinoyoti** [slick/slick#1558]
I'm having a really hard time to figure out how to properly use transactions at my controller level in slick. I'm finding it hard to believe it's not possible at all, since a lot of real world use cases require that. 

I can understand how composing by query or action is preferable and that transactionality in those cases just works. However, considering code like this:

```
class UserController @Inject(userService: UserService) {
  def register(userData: UserData) = {
    userService.save(userData).map(result => Ok(result))
  }
}

class UserService @Inject(userDao: UserDao, addressDao: AddressDao) {
  def save(userData: UserData) = {
    for {
      savedUser <- userDao.save(userData.toUser)
// A lot of complex logic that makes checks and validates stuff
      savedAddress <- addressDao.save(userData.addressData.toAddress)
    } yield savedUser.copy(address = savedAddress)
  }
}

class SlickUserDao {
  def save(user: User) = {
    db.run((UserSchema.users returning UserSchema.users)).insertOrUpdate(user)
  }
}
```

UserService calls two Daos to do inserts. I want the execution of my controller to be atomic and both operations should be commited or none at all.

On the other hand, UserService is my business layer. I have loads of business logic here (despite the simplified example) and I want it to be just that: business code. I don't want it polluted with framework specific dependencies, such as slick, so return DBActions and explicitly calling `database.run(action)` is not an option. 

I tried to create my own session handling code, despite the fact it forces me to pass my session identifier between methods in my business layer, as well as start and end the transaction, which is also not ideal, but I was hoping to tidy it up a bit more after I got it working.

```
object DB {

  val sessions = Map[String, JdbcBackend.Session]()

  val nightclub = JdbcBackend.Database.forConfig("nightclub")

  def createSession(): String = {
    val session = nightclub.createSession()
    session.conn.setAutoCommit(false)
    val uuid = UUID.randomUUID().toString
    sessions += (uuid -> session)
    uuid
  }

  def execute[R](action: DBIOAction[R, NoStream, Effect.All])(implicit uuidOption: Option[String] = None): Future[R] = {

    uuidOption match {
      case None => nightclub.run(action)
      case Some(uuid) => sessions.get(uuid) match {
        case None => throw new IllegalStateException("No database session opened")
        case Some(sess) =>
          sess.database.run(action)
      }
    }
  }

  def closeSession(uuid: String): Unit = {
    sessions.get(uuid) match {
      case Some(session) =>
        sessions -= uuid
        session.close()
    }
  }
}
```

Except it doesn't work. It's auto-committing every single `database.run` I do. Is `sess.database.run(action)` not 
running it within the session? I tried using `withPinnedSession` as well, but it also doesn't work.

Any help would be welcome. I find hard to believe Slick doesn't provide a way to handle these use cases. Pretty much every other persistence framework I used in the past does, one way or another. I must be missing something.

Thanks

**Comment by cvogt** [comment]
You can run a DBIOAction in a transaction by calling `.transactionally` on it before passing it to `.run`. If you want your controller to be able to control transactions, you need to return DBIOActions to the controller rather than futures and let the controller call `.run( action.transactionally )`. Also see: http://slick.lightbend.com/doc/3.1.1/dbio.html#transactions-and-pinned-sessions

**Comment by bcatarinoyoti** [comment]
I had a read at the documentation (several times) but it's hardly helpful. There's basically only one compressed paragraph about transactions and pinned sessions, with only one example of one of the cases and no documentation to explain how transactions and sessions work when using queries, actions or futures. It took me hours to test through the different scenarios, so that I could understand the implications of using one and another. And still, I felt like I was misunderstanding something, because Slick surely couldn't be that limited. I was wrong...
Regarding pinned sessions, I'm not even sure I understand what they are yet and the documentation definitely needs to improve on this subject.

As I understand slick right now, it poses several limitations to developers. It completely breaks the DAO pattern, by forcing me to expose persistence layer classes to my business logic layer, makes testing a lot harder and forces me to code my business logic in a way that suits the persistence layer, if I want to have common features like transactionality.

With that in mind, I don't think this issue is SOLVED. You may say you won't solve it and Slick will never do that because of any reason you might have, but it's definitely NOT SOLVED.

Don't get me wrong, I think you guys did an amazing job with Slick in many areas, but the limitations are way too important to ignore. Lack of documentation doesn't help. 

Do you foresee in the relatively near future doing anything about this?

**Comment by cvogt** [comment]
@bcatarinoyoti I spent too little time on your issue in my last response. Sorry about that. Like most people working on Slick I am a volunteer, who does this in my free time, which is limited.

We decided to adopt monadic Session handling in Slick 3, because we wanted to support a hand full of nice features:
* No accidental leaks of sessions, in Slick 2 this was causing runtime exceptions for example: `db.withSession(session => Future{query.list})`, because the session would be closed before the Future completed.
* Automatic scheduling of db io to a blocking execution context, while scheduling computations to a non-blocking one.
* Automatic management of sessions and transactions in a well compositional manner.
* Tracking of effects, so people can actually statically prevent accidental writes to slaves, or reads to master, which admittedly takes some extra type system knowledge to pull off. I know several parties who use this though (also see https://github.com/dwestheide/slick-effect-types).

In order to do this, database actions need to be composed in a way that Slick and the type system understand - not using side-effects. Otherwise you can't achieve the above benefits well or at all. Other libraries like Doobie went down the same route. As you discovered this does indeed require your DAO's internal types to be explicit about composing actions. If you use Slick's composable action - yes that ties it to Slick. You could use Doobie's instead (which have not been preconfigured for Slick obviously). You could also likely go ahead and abstract over which concrete Monad type is used, but at least an abstract one would be required, but wouldn't tie you to a framework. Of course that takes more knowledge of the type system to create and maintain.

There are situations however where "infecting" everything with the monadic return type can be impractical. I actually argued for supporting a break-out hack out of the box for these cases, where you leave the safe environment but get more flexibility (see https://github.com/slick/slick/pull/1082). @szeiger and I couldn't align on this back then, but the situation has changed a bit since.

Implementing this break out hack should actually not be too hard, if you want to give it a shot. You'd probably just need a new Action type that exposes the JdbcConnection in a block, and an alternative runUnsafe, that can allows running Slick queries given a JDBC connection. 
```
val action = unsafeAction{
  jdbcConnection => 
  db.runUnsafe( query.result )( jdbcConnection )
}: DBIO[...]
db.run(action)
```

Also, there there is general openness to simply bringing the blocking Slick 2.x api back as an alternative, if somebody ports it to 3.x and opens a PR. There are no concrete plans, but we are open to it. If we are lucky time-wise @radsaggi may be able to squeeze some time out for this in August.

Please let me know if this was helpful at all.

**Comment by bcatarinoyoti** [comment]
That's alright, I understand it's mostly free effort people put in it and I appreciate all the good stuff Slick offers to developers. But this transactionality limitation is really frustrating and I do feel like I made the wrong framework choice in this particular case.

I'm not sure I fully understood the hack you mentioned. I'm guessing this custom action would have a reference to the JDBC connection itself and would allow to start and end the transaction, right? I did try during these past days create a layer that stores the sessions with a UUID identifying it (as described in my first post), but I guess that wouldn't work, because the operations would be committed by then.

I wouldn't have much more time to implement what you suggest. I already spent a couple of days just trying to figure out how slick deals with transactions (documentation could be improved as well), so I might have to just bite the bullet and implement it as Slick allows to do now. I don't like how it infects the business layer, but I'll try to keep it to a minimum and with more time in the future, I might try to come up with some alternative, if nothing exists yet.

But any improvements of the kind to the framework, if you do have opportunity to do it, would be welcome.

**Comment by cvogt** [comment]
you could set the transaction on the jdbc session, but you wouldn't need to. This should keep the transaction open:

```
val action = unsafeAction{
  jdbcConnection => 
  db.runUnsafe( query.result )( jdbcConnection )
}: DBIO[...]
db.run(action.transactionally)
```

if you don't want to even pass through the jdbcConnection, you could store it in a threadLocal, which is what Slick used to allow with: `db.withDynSession{ ... }`, but the more you reside to side-effects, the harder your code becomes to get right :).

**Comment by cvogt** [comment]
closing in favor of this: #1563
