### ISSUE TITLE
can't delete record

### ISSUE THREAD

**Issue by ghost** [slick/slick#156]
I write follow statement to delete one db record:
EmpDepartments.where(ed => (ed.empId is it) && ed.endDate.isNull).delete
the compiler say:
value delete is
 not a member of scala.slick.lifted.Query[models.EmpDepartments.type,scala.slick
.lifted.NothingContainer#TableNothing]
when I change to
Query(EmpDepartments.where(ed => (ed.empId is it) && ed.endDate.isNull)).delete
compile error change to:
Don't know how
to unpack scala.slick.lifted.Query[models.EmpDepartments.type,scala.slick.lifted
.NothingContainer#TableNothing] to U and pack to R

Very strange, sometimes compile is ok and run result also ok. finally, i replace it with NativeQuery, I really like scala style query or update, please fix this issue.

**Comment by hanfeisun** [comment]
same issue..

> Is there a recommended way to abstract a Jdbc driver here?

**Comment by hanfeisun** [comment]
solved, `delete` is not available because I mixed the usage of `import play.api.db.slick.Config.driver.simple._` and `import scala.slick.driver.PostgresDriver.simple._`.. After I replace all `scala.slick.driver.PostgresDriver.simple._` by `import play.api.db.slick.Config.driver.simple._`. It works again.
