### ISSUE TITLE
`CleanUpAction` hungs if the clean-up action throws an exception

### ISSUE THREAD

**Issue by federico-pellegatta** [slick/slick#1585]
## Description

A `CleanUpAction` hungs, when runned, if the provided clean-up action throws an exception. The returned future is never completed.
## How to reproduce

``` scala
def runCleanUpAction[R](database: Database, action: DBIOAction[R, NoStream, Nothing]): Future[R] = action.cleanUp(_ => throw new Exception())
```
## Cause

I have traced back the root cause to how `CleanUpAction`s are managed within `DatabaseDef.run` [BasicBackend.scala#L191](https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/basic/BasicBackend.scala#L191). 

In order to expose the same behaviour I have written a small snippet:

``` scala
import scala.concurrent.{ Promise, Future, Await }
import scala.concurrent.duration.Duration
import scala.concurrent.ExecutionContext.Implicits.global
import scala.util.control.NonFatal

def runInContext: Future[Unit] = {
  val p = Promise[Unit]()
  Future(Unit).onComplete { 
    t1 => throw new Exception()
  }
  p.future
}

def runInternal: Future[Unit] = {
  try runInContext
  catch { case NonFatal(ex) => Future.failed(ex) }
}

Await.ready(runInternal, Duration.Inf)
```

**Comment by calippo** [comment]
+1

**Comment by hvesalai** [comment]
This happens on row 

https://github.com/slick/slick/blob/ebfdc09c687e5177358cdc3783e8493f6317bd53/slick/src/main/scala/slick/basic/BasicBackend.scala#L187

Where the exception is thrown, but since we are running inside "onComplete" there is nobody who handles it. Instead of throwing the Exception here, the promise should be completed with the exception (unless already completed, in which case the Exception can be discarded -- possibly logging it first).
