### ISSUE TITLE
Dynamo db support in slick

### ISSUE THREAD

**Issue by Khalian** [slick/slick#1629]
Does slick dynamo db. If not would guys be interested in community contributions for the same?

**Comment by dant3** [comment]
Dynamo db is nosql database, much like mongo, riak or maybe cassandra. I'm
not sure if slick is a good match for working with it.

**Comment by cvogt** [comment]
Would likely not be super easy to pull off and resources to assist/review are a bit limited in the Slick team at the moment. So I would classify that as out of scope right now, but I am only one voice here.

**Comment by trevorsibanda** [comment]
I've been working on support for a couple of dbs.

Have a workjng...ish monetdb profile and been tinkering with voltdb.

 Just started out at varsity so I've been a bit time constrained lately. But the biggest problem or obstacle rather to supporting NoSQL would be Slick's high dependence on JDBC. I think only MongoDB has some form of a jdbc wrapper and even then it would feel hacky. It was attempted by a previous GSOC student and never finished.

https://github.com/dvinokurov/slick/tree/tmp/mongodb

**Comment by adamkozuch** [comment]
Actually I was working on that project during GSOC 2016. The attemp was to write separated query compiler for mongodb. Quite a lot of things changes since project from 2014. Afterwards because of studies and work I didn't have enough time to work on it. Now I have a bit more time and I would like to start work on it again. It's quite complex project so if you guys have some ideas or a bit time to look into code it would be great. The project is here : https://github.com/adamkozuch/Slick-MongoDB-Driver
