### ISSUE TITLE
Syntax error in CREATE TABLE statement

### ISSUE THREAD

**Issue by smartnose** [slick/slick#1654]
I was running a [slick template project](https://github.com/cdiniz/slick-akka-http-oauth2) against PostgreSQL and MySQL. Both of them complaining about the generated SQL syntax:

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"accounts" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL ' at line 1

This is the generated SQL:
create table "accounts" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"email" VARCHAR NOT NULL,"password" VARCHAR NOT NULL,"created_at" TIMESTAMP NOT NULL)

These are the versions:

version       := "0.0.1"

scalaVersion  := "2.11.7"

scalacOptions := Seq("-unchecked", "-deprecation", "-encoding", "utf8")

libraryDependencies ++= {
  val akkaV = "2.4.2"
  val sprayV = "1.3.3"
  val slickV = "3.1.1"

**Comment by smartnose** [comment]
A couple of things are not right in the syntax:

The table name should not be quoted.
VARCHAR must have length limit

Looking at [MySQLDriver](https://github.com/slick/slick/blob/3.1.1/slick/src/main/scala/slick/driver/MySQLDriver.scala) and [JDBCStatementBuilder](https://github.com/slick/slick/blob/3.1.1/slick/src/main/scala/slick/driver/JdbcStatementBuilderComponent.scala). It does seem to be the case that the table names are always quoted for MySQL?

**Comment by cvogt** [comment]
Taking super quick look it looks like this inofficial template project is hard-coded against H2 as you can notice from `import slick.driver.H2Driver.api._` in this and other files https://github.com/cdiniz/slick-akka-http-oauth2/blob/master/src/main/scala/persistence/dals/AccountsDal.scala

It looks like it is generating H2 queries but trying to run them against postgres or mysql. In order to make the driver swappable, a project needs to be well prepared.

This ticket is somewhat related https://github.com/slick/slick/issues/1638

**Comment by cvogt** [comment]
This seems to be a misusage of the admittedly tricky way to abstract over different backends. So closing this. Please re-open if there are more indications for this being a bug.

**Comment by smartnose** [comment]
Thanks cvogt. Was suspecting this might be the reason, but couldn't nail the root cause.
