### ISSUE TITLE
How to enable logging for slick without xml?

### ISSUE THREAD

**Issue by doofin** [slick/slick#1834]
Searching around the web I know there are ways to set up logback with slick but inevitably there are bunch of xml involved,so I tried to replace slf4j-nop with "org.slf4j" % "slf4j-simple" % "1.8.0-beta0", but that doesn't work,there is noting printed to console.Using xml is neither friendly nor safe,and setting the path of it is tricky sometimes so I wish to just put the configs to a scala or sbt file.Thanks!

**Comment by sarahgerweck** [comment]
@doofin this is not a Slick issue: SLF4J is the standard logging infrastructure across the JVM ecosystem. I recommend that you use Logback, but there are other SLF4J implementations available like Log4j2.

The configuration involved to use Logback is not particularly complicated if you just look for some examples. You just need to make a `logback.xml` file and put it in your `src/main/resources` directory. You will be doing yourself a favor if you learn to use XML and Logback. They are both pretty simple and you will encounter them often if you are working on the JVM. Logback also gives the option to write your configuration in Groovy.

(Log4j2 also uses XML as its default configuration mechanism. XML remains popular for use cases like this because it's flexible, standard, type safe and machine verifiable.)
