### ISSUE TITLE
Upgrade HikariCP to 3.x (for now 3.1.0 is newest)

### ISSUE THREAD

**Issue by margussipria** [slick/slick#1902]
For now `slick-hikaricp` supports 2.x and calls deprecated method(s) with latest 2.x release (2.7.9), but HikariCP 3.0.0 removed all deprecated methods.

When manually upgraded to 3.1.0 and running project following exception is thrown:
```
java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariConfig.setInitializationFailFast(Z)V
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:44)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:21)
```

**Comment by hvesalai** [comment]
Thank you for the report. However I'm closing this issue to keep the issue database slim. We will notice this when and if we update the hikari version and the method is gone (things just won't compile).

Rather than making an issue, I would gladly accept a PR that made the actual upgrade along with fixing any calls to deprecated or removed methods.
