### ISSUE TITLE
Slick and database views

### ISSUE THREAD

**Issue by felixoi** [slick/slick#1933]
I've a complex view created in my postgres database and now I wanna query with it in slick. I haven't found any good solution for this up to now. The onliest solution would be to create a direct database statement through slick but that's not my intention. So how to use database views with slick?

**Comment by Asamsig** [comment]
Please use the gitter channel for questions, this is the issue tracker for the Slick project, so limit issues here for improvement suggestions, feature requests or bugs.

As for your question there should be no magic with Slick in this case. You can write your Slick schema definition in accordance to your view, and then use Slick as you otherwise would. The only limitation in Slick currently has with views as far as I know, is that it can't generate Slick schemaes from SQL.

**Comment by Daxten** [comment]
You can generate them, it just doesn't do it automaticly

```
val tables   = slick.jdbc.meta.MTable.getTables(None, None, None, Some(Seq("VIEW", "TABLE")))
```

and then run the codegen on those

**Comment by Asamsig** [comment]
It actually also depends on which `Profile`, since some profiles don't filter on what to generate, and will there generate Views by default. What I actually meant in my previous comment, was that you can generate Slick schemas from SQL Views, but you can't generate a View SQL schema from a Slick schema, since Slick doesn't have special handling for Views.

**Comment by trevorsibanda** [comment]
closing this.
