### ISSUE TITLE
multiple flatmap and zip do not work consistently in update

### ISSUE THREAD

**Issue by gurgec** [slick/slick#1989]
**DESCRIPTION:**
When we create several DBIOActions with flatMap and zip the actions. If the first action is update the other actions do not work properly.
**STEPS TO REPRODUCE:**
1. I have DBIOAction defined as. 
`val validRecordsAction: DBIOAction[Seq[Long], NoStream, Effect.Read] = existingRecords.result.map { existingRecords: Seq[Books] =>
      existingRecords.filter((elem: Book) => isStatusChangeValid(elem.Status,newStatus))
    }`
2. I have one update 4 get actions on this DBIOAction.
```
val updateActions: DBIOAction[Int, NoStream, Effect.Read with Effect.Write] = validRecordsAction.flatMap { ids: Seq[Long] =>
      bookTable.filter(_.book_id.inSet(ids)).map { record =>
        (record.status, record.last_modified_date, record.last_modified_by)
      }.update(Some(newStatus), Some(Timestamp.valueOf(LocalDateTime.now(ZoneOffset.UTC))), Some(user.userId))
    }
val getBookSetResultGroupByArticleAction: DBIOAction[Seq[GroupByArticleSetResponse], NoStream, Effect.Read] = validRecordsAction.flatMap(BookSqlActions.getBookSetResultGroupByArticle)
```

3. On db.run(updateActions zip getBookSetResultGroupByArticleAction) I see that the valid record ids do not included in the getBookSetResultGroupByArticle statements and result is wrong.

**EXPECTED RESULT:**

I expect I can get results of validRecordAction results in getBookSetResultGroupByArticleAction after zip update.
**ACTUAL RESULT:**
I could not get results of validRecordAction in getBookSetResultGroupByArticleAction if I zip it with update. But when I do zip in reverse order db.run getBookSetResultGroupByArticleAction zip updateActions) there is no problem to get results.
**SETUP:**

I am using Slick 3.2.3 with MYSQL DB.

**Comment by hvesalai** [comment]
Could you please clarify this issue. The Expected and Actual Result section is supposed to describe what you expected to get and what you got respectively, but now it describes the problem, not what was the result of the code.

**Comment by WellingR** [comment]
`updateActions` is derived from `validRecordsAction`, since you use `val updateActions = validRecordsAction.flatMap { ...`

This means that the `validRecordsAction` will be executed, and then the `updateActions`

In addition you have `val getBookSetResultGroupByArticleAction = validRecordsAction.flatMap(BookSqlActions.getBookSetResultGroupByArticle)`


If you execute the `getBookSetResultGroupByArticleAction` after the `updateActions` then the `validRecordsAction` will be evaluated a second time. This means that the update action may have caused the `validRecordsAction` to return something different. Which is probably the cause of your problems.

If you are executing queries and updates, then the order of these statements matters.

**Comment by hvesalai** [comment]
Closing because of no response from the original author. If you wish, you can reopen the issue with clarifying comments.
