### ISSUE TITLE
Oracle has taken down oracle-xe-11g

### ISSUE THREAD

**Issue by hvesalai** [slick/slick#1993]
Our builds are failing because Oracle has DMCA takedown'ed the docker image we use for testing.

See https://github.com/wnameless/docker-oracle-xe-11g/issues/118

**Comment by deusaquilus** [comment]
We're trying to build Oracle support into Quill and having exactly the same problem. The official 12c Oracle image on DockerHub is unuseable because it requires DockerHub credentials which Travis and Circle don't support for public PRs because of obvious security issues. I complained on the Oracle docker pages (oracle/docker-images#1156) but don't get your hopes up.

**Comment by WellingR** [comment]
This has already been fixed as part of https://github.com/slick/slick/commit/684735948ae64df17de62e3627c9f4705c6e1b2d
