### ISSUE TITLE
Silent insert/update failures in 3.3.0

### ISSUE THREAD

**Issue by seanmorton** [slick/slick#2011]
**DESCRIPTION:**

My team recently upgraded from Slick 3.2.1 to Slick 3.3.0, and we started noticing silent failures in some of our application's inserts & updates. For the update case, Slick would report that a nonzero number of rows were updated (success), but when inspecting the database rows, no updates were actually made.

Interestingly the bug only seemed to surface for specific columns and tables, i.e. we consistently were not able to update a specific column in one of our tables, and also could not insert entire tuples into certain tables. 

Performing identical updates & inserts manually in the `psql` console were successful.

Downgrading back to 3.2.1 fixed the issue for us.

This may be a version compatibility issue, as our system is a little behind in related software (see SETUP below.)

**STEPS TO REPRODUCE:**

This is a simplified version of Slick code in our application that is experiencing the problem:
```
    val action = for {
      updatedCount <- Tables.SomeTable
        .filter(tuple => tuple.id === id)
        .map(tuple => (tuple.columnToUpdate))
        .update(value)
      result <- updatedCount match {
        case 0 => DBIO.Failed(Error("Failure: 0 rows updated."))
        case 1 => DBIO.successful()
        case _ => DBIO.Failed(Error("Failure: Multiple rows were updated."))
      }
    } yield result

    db.run(action)
```

**EXPECTED RESULT:**

The above action should return `DBIO.successful`, and the column `SomeTable.columnToUpdate` for `id` should be updated with `value`.

**ACTUAL RESULT:**

The above action returns `DBIO.successful`, but the column `SomeTable.columnToUpdate` for `id` **is not** updated with `value`.

**SETUP:**
* PostgreSQL 9.6.11, JDBC Driver postgresql:41
* Also using [slick-pg](https://github.com/tminglei/slick-pg) @ v0.15.3

**Comment by parallelepiped** [comment]
Being on the same team, I second this issue

**Comment by hvesalai** [comment]
It would be good if you could debug this your self more. To start with, I would advice you to turn on the logging of sql statements in the DB and see what (if anything) is being executed when this happens.

**Comment by seanmorton** [comment]
Thanks for the prompt reply. We won't be able to debug any further for now due to other priorities, but once we prioritize upgrading again I will share our debug results here.

**Comment by WellingR** [comment]
You state that you are using the version 41 of the postgres JDBC driver. Slick 3.3.0 was built and tested using 42.2.2. My recommendation is to upgrade to the latest 42.2.x version of the postgres driver.

In addition, you state your are using slick-pg v0.15.3, this version was build and tested using slick v3.2.1. It is very likely that slick-pg v0.15.3 is NOT compatible with slick 3.3.0.

To be certain that this is indeed a bug in slick I would like to know the following:
- Can you reproduce the issue using slick-pg v0.17.2 (or later), using the latest 42.2.x postgres driver?
  - If so, then can you produce a minimal example demonstrating this issue?
- Can you reproduce the issue without using slick-pg, using the latest 42.2.x postgres driver?
  - If you can reproduce this without using slick-pg then we can be certain that this is not a slick-pg issue.
- Can you reproduce this issue using slick-pg v0.17.1 in combination with slick v3.2.3
  - If not, then we know the issue was introduced between versions 3.2.3 and 3.3.0
