### ISSUE TITLE
ibmcom/db2express-c repository no longer exists

### ISSUE THREAD

**Issue by eed3si9n** [slick/slick#2051]
## steps

Send a pull request.

## problem

```
+docker run -d -p 50000:50000 --name db2slick -e DB2INST1_PASSWORD=db2inst1-pwd -e LICENSE=accept ibmcom/db2express-c:latest db2start
Unable to find image 'ibmcom/db2express-c:latest' locally
docker: Error response from daemon: pull access denied for ibmcom/db2express-c, repository does not exist or may require 'docker login'.
```

## expectation

Tests passes.

## notes

https://hub.docker.com/_/db2-developer-c-edition says it has moved to https://hub.docker.com/r/ibmcom/db2. Simply changing `ibmcom/db2express-c:latest` to `ibmcom/db2:latest` with `--privileged=true` also failed https://travis-ci.org/slick/slick/jobs/556420527#L573-L574:

```
+docker cp db2slick:/home/db2inst1/sqllib/java/db2jcc4.jar .
Error: No such container:path: db2slick:/home/db2inst1/sqllib/java/db2jcc4.jar
```

**Comment by WellingR** [comment]
The command `docker cp db2slick:/home/db2inst1/sqllib/java/db2jcc4.jar` probably fails because the jdbc driver is not in that directory in the new container. It is worth investigating if the jar is available in some other location in the container.
Otherwise we need some other mechanism to include the jdbc driver jar (something similar to what is done for the oracle driver probably)

**Comment by WellingR** [comment]
It seems that the container does contain the driver jar. It can be found in
`/opt/ibm/db2/V11.5/db2tss/lib/db2jcc4.jar`
`/opt/ibm/db2/V11.5/java/db2jcc4.jar`

I am currently testing if this works
