### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by SethTisue** [slick/slick#2177]
Stefan made an initial stab at it in https://github.com/slick/slick/pull/2123, which was never merged

a volunteer is needed to rebase and resubmit it, updating it from an old Dotty version to a current Scala 3 version

**Comment by SethTisue** [comment]
new PR: #2187

**Comment by nafg** [comment]
I pushed a rebase as nafg/dottyquery

**Comment by xuwei-k** [comment]
Is there any updates? 👀

**Comment by nafg** [comment]
3.4.0 is almost out (published RC2 already) and then it's my top priority for Slick.

I've been keeping the `nafg/dottyquery` branch rebased but it needs more work.

For example IIUC currently it deletes scala 2 macros when it could instead use scala-version-specific directories.

**Comment by nafg** [comment]
Also I'm not 1,000% certain that I haven't deleted or broken anything when I rebased and tried to resolve conflicts. So it will need testing too of course.

**Comment by collymy** [comment]
Any news on Scala 3 support?

**Comment by nafg** [comment]
Not yet, sorry. I want to get other PRs merged first and then it's my top Slick priority.

**Comment by nafg** [comment]
I'll try to post updates to this issue. Right now I'm working on getting #2398 merged.

**Comment by nafg** [comment]
I would get more Slick work done if someone would pair with me (even just to watch)

**Comment by ameen-elhoseiny** [comment]
Hello,
any updates for this ?

**Comment by anqit** [comment]
> 

hi @nafg , I would love to hop on a pairing session, though I'm new to slick, so I'm not sure how much value I'd add besides just being present.

**Comment by nafg** [comment]
@anqit that would be super helpful. Do you want to follow up on Discord?

**Comment by anqit** [comment]
@nafg sure! I'm @anqit in the scala discord as well

**Comment by MohammadForouhesh** [comment]
Any updates with this regard?

**Comment by nafg** [comment]
Hi, something came up and I've been very busy lately, but hopefully a week from Sunday I'll be back on the job.

I already released https://github.com/slick/slick/releases/tag/v3.5.0-M1 on January 11th, so this is absolutely at the top of the list.

**Comment by jimm-porch** [comment]
For what it's worth, I spent some time today trying to use the Scala 2 artifacts with a Scala 3 testbed.

At my employer we have an internal Slick library which forces everyone to configure their Slick repos in the same way. 
 Originally it was cross-compiling for 2.11 - 2.13 on Slick `3.3.1`, and I tried making a Slick 3 build based on `3.5.0-M2`.

I was feeling optimistic for a while because I was able to get the dependencies to work, and our standard library code didn't require too many adjustments to account for the changes introduced since Slick 3.3.1.  (Like `JdbcProfile#API` being renamed to `JdbcProfile#JdbcAPI`, etc)

But ultimately I had to give up because there are some key features of Slick which are only implemented as Slick 2 macros, and those aren't supported by the Scala 3 compiler.  For example the `sql""` and `sqlu""` string interpolators are macros.

There were some idioms which use macros which we _were_ able to avoid, with small changes in syntax.  For example the declaration of `TableQuery` instances:

```scala
// In Slick 3.3
val queryUsers = TableQuery[UserTable]

class UserTable(tag: Tag) extends Table[User](tag, Some(schemaName), "user")
```
```scala
// In Slick 3.5 we can avoid the macro by passing the UserTable constructor,
// which results in a very similar syntax if we make the table a case class.
// Just change [T] to (T)
val queryUsers = TableQuery(UserTable)

case class UserTable(tag: Tag) extends Table[User](tag, Some(schemaName), "user")
```

But in the end, some features are so reliant on macros that we're stuck until a native Scala 3 release comes out.

**Comment by nafg** [comment]
`nafg/dottyquery` compiles, and it's available in #2687

**Comment by nafg** [comment]
@jimm-porch hopefully in a few weeks with G-d's help

**Comment by martinring** [comment]
Is there any news on this issue?

**Comment by nafg** [comment]
Certainly. I just released 3.5.0-M3, with G-d's help, which incorporates all the major removals and breaking changes from the `dottyquery` branch, which is rebased on top of it. So now all that's left, I think, is rebasing the remaining commits so it's not so messy. That is of course, barring any important feedback from people who try M3 and need any changes to the current plan.

I suppose I should post this on reddit, and make the release page more clear, but let me sum it up here for now:

Everyone should try out M3 and give feedback ASAP, to ensure the changes in 3.5.0 are acceptable. See https://github.com/slick/slick/releases/tag/v3.5.0-M3

**Comment by mdedetrich** [comment]
@nafg If it hasn't already been done so, would it be possible to update the Scala 3 to 3.3.0 LTS since that is the version that is strongly recommended for library authors to use?

**Comment by mdedetrich** [comment]
> I don't remember which milestone dropped 2.12 but it should say.

So I just checked the releases and it seems like 3.5.0-m2 itself dropped Scala 2.12, see https://github.com/slick/slick/releases/tag/v3.5.0-M2 which is the milestone version just before this one.

> Maintaining 3 versions would be a lot harder. Sponsoring or otherwise sharing that burden might make it worthwhile. Either way happy to discuss in a call next week.

So I found the original pull request that removed Scala 2.12 support (see https://github.com/slick/slick/pull/2633) and the PR just removes Scala 2.12 from `CrossScalaVersions`/CI etc etc). So unless I am missing something than it doesn't seem like Scala 2.12 had any real maintenance burden, if this is the case would you be happy reverting that PR?

I also don't have an issue in helping keep Scala 2.12 support, as an aside and some context Pekko is supporting Scala 2.12 all the way to Scala 3 however we will at some point decide to drop Scala 2.12, its just a decision that we will make in the future as a community. It would be however nice from our side if at the least the first version of Pekko 1.0.x can support Scala 2.12 all the way to Scala 3 to make for the people that need to migrate as well as the people using Scala 3.

**Comment by mdedetrich** [comment]
@nafg I apologize for my previous comment, I didn't realize the path you took for integration Scala 3 into slick was by feeding Scala 3 compatible code into Scala 2 versus the other way around. This obviously makes is significantly more difficult to support Scala 2.12 along with Scala 2.13/Scala 3 since Scala 2.12 doesn't have the ability to accept Scala 3 syntax.

Hence you can ignore the Scala 2.12, I will try and figure a way around it. If the difference between Slick 3.4.1 and Slick 3.5.x isn't that big then we can probably get away with just release pekko-persistence-jdbc 2.12 using an older version of Slick.

The only thing I did notice when trying out `3.5.0-M3` is that I couldn't seem to find the Scala 3 artifact/s for it? According to Maven it exists but only for 2.12/2.13 (see https://mvnrepository.com/artifact/com.typesafe.slick/slick) and as you can tell from

```
[error]   not found: /Users/mdedetrich/.ivy2/local/com.typesafe.slick/slick_3/3.5.0-M3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/slick/slick_3/3.5.0-M3/slick_3-3.5.0-M3.pom
[error]   not found: https://repository.apache.org/content/repositories/snapshots/com/typesafe/slick/slick_3/3.5.0-M3/slick_3-3.5.0-M3.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/slick/slick_3/3.5.0-M3/slick_3-3.5.0-M3.pom
[error]   not found: https://s01.oss.sonatype.org/content/repositories/snapshots/com/typesafe/slick/slick_3/3.5.0-M3/slick_3-3.5.0-M3.pom
[error]   not found: https://jcenter.bintray.com/com/typesafe/slick/slick_3/3.5.0-M3/slick_3-3.5.0-M3.pom
```

The dependency resolution is failing.

**Comment by nafg** [comment]
It's not published for Scala 3 yet. The last milestone was about integrating changes from the original PR that are breaking changes to the API. The point is that before/while working on Scala 3 support, existing users can see if any of the breaking changes affect them and they want to share that feedback. (I guess dropping 2.12 is one case of that!)

Bringing 2.12 back might not be an issue (other than long CI times). If it's important open a PR bringing it back. But I think it would be good to have a call.

**Comment by mdedetrich** [comment]
Definitely up for doing a call, I just feel slightly guilty in pushing for this because at least my impressions is that it would take a bit of effort.

@nafg What timezone are you in? I currently am in CEST but in general am quite flexible regarding call

**Comment by nafg** [comment]
3.5.0-M4 is now on maven central, cross-published for 2.12, 2.13, and 3.2.2!

**Comment by mkurz** [comment]
AFAIK it's recommended that from now on libraries should use Scala 3.3.x. Any reason to stay on 3.2.2?

**Comment by mkurz** [comment]
@mdedetrich :+1: missed that one

**Comment by nafg** [comment]
@mkurz as you can see in #2756, 3.3.0 crashes (at least with code coverage). But a you can see in #2758, 3.3.1-RC3 is fixed. Since 3.3.1 is not due for a week I figured it's best to get something on maven central already so downstream projects can test.

It's only a milestone release after all.

**Comment by mkurz** [comment]
@nafg Got it thanks, how about a M5 with #2758 merged then?

**Comment by nafg** [comment]
Sure
