### ISSUE TITLE
Some Travis builds are are failing due to Docker Hub rate limiting

### ISSUE THREAD

**Issue by nafg** [slick/slick#2211]
For instance https://travis-ci.com/github/slick/slick/jobs/498593711

https://blog.travis-ci.com/docker-rate-limits has instructions to avoid this

**Comment by SethTisue** [comment]
I'll find out if Lightbend has an account we could use.

**Comment by nafg** [comment]
Any free account would allow twice as much as anonymous usage. But if the
account is used elsewhere then obviously its total usage is constrained.

**Comment by SethTisue** [comment]
"The only dockerhub account we had (that I am aware of), we shut down a few months ago.", says Justin P

**Comment by octonato** [comment]
We don't have a dockerhub and we decide to not make one for Play/Lagom/Akka because we have had lots of issues with Travis in the past (even in the paid plans we have for Lagom and Play).

Our strategy is to move to GitHub Actions. GH Actions is not yet as flexible as Travis and the build config requires some silly repetition. 

Still, we believe that it is here to stay (and will probably eat all the other CI for lunch).

GitHub Actions are not rate limited by Docker Hub (they seem to have an agreement). 

I suggest to move to GH Actions sbt-ci-release. I have started to do that in a few Akka projections. You can have a look on the [akka projection PR](https://github.com/akka/akka-projection/pull/528) for some inspiration.

Note that I created different workflows per database type. The reason for that is that GH Actions don't allow you to restart a single job, only the workflow. Databases with docker can be flaky and I don't want restart all jobs because of a single flaky DB tests. 

Many workflows force you to repetition, but it's not that much and it pays off, IMO.
