### ISSUE TITLE
Add support for "SELECT DISTINCT"

### ISSUE THREAD

**Issue by aloiscochard** [slick/slick#96]
It would be nice to be able to call ".distinct" on Query, instead of having to '.run.distinct' or '.to[Set]' which move all duplicates on the wire.

Cheers

**Comment by cvogt** [comment]
distinct is still not in

**Comment by toby5box** [comment]
I could also use `distinct` in 2.1.0. Is this not going to happen on the 2.1 series? :/

**Comment by nafg** [comment]
3.0.0 was already released

**Comment by gatorcse** [comment]
+1 this

**Comment by gregsilin** [comment]
Is there a target version for this?

**Comment by pkinsky** [comment]
+1, is there a workaround for this besides hand written SQL?

**Comment by toby5box** [comment]
@pkinsky Yes, but I don't think it compiles into DISTINCT:

`.groupBy(identity).map(_._1)`

**Comment by szeiger** [comment]
I just took a stab at this based on the 3.1 query compiler but it turns out to be trickier than I thought. Take the following schema and data:

```
    class A(tag: Tag) extends Table[(Int, String, String)](tag, "A_NEWFUSION") {
      def id = column[Int]("id", O.PrimaryKey)
      def a = column[String]("a")
      def b = column[String]("b")
      def * = (id, a, b)
    }
    val as = TableQuery[A]

    val data = Set((1, "a", "a"), (2, "a", "b"), (3, "c", "b"))
```

Now `as.map(_.a).distinct` trivially gives you `Seq("a", "c")` (leaving ordering aside). But what about `as.distinct.map(_.a)`? I think we can all agree that `Seq("a", "a", "c")` is the correct answer because that is the result of the equivalent computation `data.toSeq.distinct.map(_._2)` in Scala.

But how do we get there? Slick does not know the complete, real set of columns. What it does know is the star projection, so that `as.distinct.map(_.a)` would be equivalent to `as.distinctOn(_.*).map(_.a)` (i.e. every `distinct` starts as a `distinctOn` with a mapping that star-expands all table types; we do the same for the final result of a query). Assuming that most database systems do not support `distinct on`, an optimizer step then needs to rewrite this into a subquery with a simple `distinct` if possible, and otherwise (when the star projection is incomplete and a later step needs a column that is not part of it) turn it into an equivalent `group by` operation.

**Comment by matanster** [comment]
Thanks!

**Comment by gregsilin** [comment]
Thanks so much @szeiger
