### ISSUE TITLE
Consider transactions as succesful for specific exception types in withTransaction

### ISSUE THREAD

**Issue by dozed** [slick/slick#979]
Sometimes it is useful to be able to ignore a specific exception when executing a function in withTransaction. An example:

```scala
class RedirectException extends ControlThrowable

db withTransaction {
  doDbStuff
  throw new RedirectException
}
```

The RedirectException here is part of the control flow and should have no impact on the success state of the transaction.

A solution could be to configure the ignored exceptions when creating the Database object.

Also see: [http://www.scala-lang.org/api/current/index.html#scala.util.control.ControlThrowable](http://www.scala-lang.org/api/current/index.html#scala.util.control.ControlThrowable)

**Comment by cvogt** [comment]
@szeiger but this isn't implemented for the Action monad, right? So shouldn't this stay open and be basically refocused on the Action?

**Comment by szeiger** [comment]
ControlThrowable doesn't really make sense in the Action API. 

In fact if you did get a ControlThrowable in there (or some other Exceptions which are not really fatal but are treated as such by scala.control.NonFatal), the caller would never receive it (i.e. the Future wouldn't complete). I consider this a design problem of NonFatal (it conflates "you don't normally want to catch this" with "it leaves the JVM in a bad state so you should never catch it") but it is consistent with error handling in Futures. Fused synchronous Action conbinators use it for this reason, so that the semantics are identical to their non-fused counterparts (where the Action combinator is lifted to a Future combinator).

The wrongly ignored exception types shouldn't normally occur when running an Action. None of the built-in Actions and combinators throw them, and user code has to written in a monadic style using the combinators.

As far as transactions are concerned, there are no explicit commit / rollback operations in the Action API. When an Action at a transaction boundary succeeds, the transaction is committed, when it fails the transaction is rolled back. If you want to treat certain exception types in a special way, you can use `asTry` to reify the exception to a successful value.

**Comment by cvogt** [comment]
I suppose asTry solves this
